// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Jai Sogani. Licensed under the Apache License, Version 2.0.

/**
 * `backend.design_schema` — generate a database schema in one of four formats.
 *
 * Input is a tiny *intermediate model* the caller assembles from requirements;
 * output is real, syntactically-valid DDL/code for SQL, Prisma, Django ORM, or
 * SQLAlchemy. The intermediate model is intentionally small and deterministic
 * so this generator stays pure and unit-testable.
 */

import type { GeneratedFile, SchemaFormat } from "./types.ts";

/** A column in the intermediate model. */
export interface Column {
  name: string;
  type: "uuid" | "string" | "int" | "bigint" | "bool" | "timestamp" | "json";
  nullable?: boolean;
  unique?: boolean;
  primary?: boolean;
  /** Optional reference to another table (foreign key). */
  references?: { table: string; column: string };
}

/** A table in the intermediate model. */
export interface Table {
  name: string;
  columns: Column[];
  comment?: string;
}

/** Options for {@link designSchema}. */
export interface SchemaOptions {
  format: SchemaFormat;
  tables: Table[];
}

/** Generate a schema in the requested format. Returns one or more files. */
export function designSchema(options: SchemaOptions): GeneratedFile[] {
  if (options.tables.length === 0) {
    throw new Error("at least one table is required");
  }
  switch (options.format) {
    case "sql": return [renderSql(options.tables)];
    case "prisma": return [renderPrisma(options.tables)];
    case "django_orm": return [renderDjango(options.tables)];
    case "sqlalchemy": return [renderSqlAlchemy(options.tables)];
  }
}

// ---- SQL (PostgreSQL dialect) --------------------------------------------

function sqlType(c: Column): string {
  switch (c.type) {
    case "uuid": return "UUID";
    case "string": return "TEXT";
    case "int": return "INTEGER";
    case "bigint": return "BIGINT";
    case "bool": return "BOOLEAN";
    case "timestamp": return "TIMESTAMPTZ";
    case "json": return "JSONB";
  }
}

function renderSql(tables: Table[]): GeneratedFile {
  const stmts: string[] = ["-- SPDX-License-Identifier: Apache-2.0", "-- Generated by Synapse Backend Architect", ""];
  for (const table of tables) {
    if (table.comment) stmts.push(`-- ${table.comment}`);
    const cols = table.columns.map((c) => {
      const parts = [`  ${c.name} ${sqlType(c)}`];
      if (c.primary) parts.push("PRIMARY KEY");
      if (!c.nullable && !c.primary) parts.push("NOT NULL");
      if (c.unique && !c.primary) parts.push("UNIQUE");
      if (c.references) parts.push(`REFERENCES ${c.references.table}(${c.references.column})`);
      return parts.join(" ");
    });
    stmts.push(`CREATE TABLE IF NOT EXISTS ${table.name} (\n${cols.join(",\n")}\n);`);
    stmts.push("");
  }
  return { path: "schema.sql", contents: stmts.join("\n") };
}

// ---- Prisma ---------------------------------------------------------------

function prismaType(c: Column): string {
  const base = (() => {
    switch (c.type) {
      case "uuid": return "String";
      case "string": return "String";
      case "int": return "Int";
      case "bigint": return "BigInt";
      case "bool": return "Boolean";
      case "timestamp": return "DateTime";
      case "json": return "Json";
    }
  })();
  return c.nullable && !c.primary ? `${base}?` : base;
}

function renderPrisma(tables: Table[]): GeneratedFile {
  const header = `// SPDX-License-Identifier: Apache-2.0\n// Generated by Synapse Backend Architect\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\ndatasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;
  const models = tables.map((table) => {
    const lines = table.columns.map((c) => {
      const parts = [`  ${c.name}`, prismaType(c)];
      const attrs: string[] = [];
      if (c.primary) attrs.push("@id");
      if (c.unique && !c.primary) attrs.push("@unique");
      if (c.type === "uuid" && c.primary) attrs.push("@default(uuid())");
      if (c.type === "timestamp" && c.primary) attrs.push("@default(now())");
      if (attrs.length) parts.push(attrs.join(" "));
      return parts.join(" ");
    });
    return `model ${pascal(table.name)} {\n${lines.join("\n")}\n}\n`;
  });
  return { path: "schema.prisma", contents: header + models.join("\n") };
}

// ---- Django ORM ----------------------------------------------------------

function djangoType(c: Column): string {
  switch (c.type) {
    case "uuid": return "models.UUIDField";
    case "string": return "models.TextField";
    case "int": return "models.IntegerField";
    case "bigint": return "models.BigIntegerField";
    case "bool": return "models.BooleanField";
    case "timestamp": return "models.DateTimeField";
    case "json": return "models.JSONField";
  }
}

function renderDjango(tables: Table[]): GeneratedFile {
  const header = `# SPDX-License-Identifier: Apache-2.0\n# Generated by Synapse Backend Architect\nfrom django.db import models\n\n`;
  const blocks = tables.map((table) => {
    const fields = table.columns
      .filter((c) => !(c.primary && c.type === "int")) // Django auto-adds id
      .map((c) => {
        const args: string[] = [];
        if (c.primary) args.push("primary_key=True");
        if (c.unique && !c.primary) args.push("unique=True");
        if (c.nullable) args.push("null=True", "blank=True");
        return `    ${c.name} = ${djangoType(c)}(${args.join(", ")})`;
      });
    if (fields.length === 0) fields.push("    pass");
    return `class ${pascal(table.name)}(models.Model):\n${fields.join("\n")}\n`;
  });
  return { path: "models.py", contents: header + blocks.join("\n\n") };
}

// ---- SQLAlchemy ----------------------------------------------------------

function sqlAlchemyType(c: Column): string {
  switch (c.type) {
    case "uuid": return "Uuid";
    case "string": return "String";
    case "int": return "Integer";
    case "bigint": return "BigInteger";
    case "bool": return "Boolean";
    case "timestamp": return "DateTime(timezone=True)";
    case "json": return "JSON";
  }
}

function renderSqlAlchemy(tables: Table[]): GeneratedFile {
  const header = `# SPDX-License-Identifier: Apache-2.0\n# Generated by Synapse Backend Architect\nfrom sqlalchemy import Column, Integer, BigInteger, String, Boolean, DateTime, JSON, ForeignKey, Uuid\nfrom sqlalchemy.orm import DeclarativeBase\n\n\nclass Base(DeclarativeBase):\n    \"\"\"Declarative base for all generated models.\"\"\"\n\n\n`;
  const blocks = tables.map((table) => {
    const lines = table.columns.map((c) => {
      const args = [sqlAlchemyType(c)];
      if (c.references) args.push(`ForeignKey('${c.references.table}.${c.references.column}')`);
      if (c.primary) args.push("primary_key=True");
      if (c.unique && !c.primary) args.push("unique=True");
      if (!c.nullable && !c.primary) args.push("nullable=False");
      return `    ${c.name} = Column(${args.join(", ")})`;
    });
    return `class ${pascal(table.name)}(Base):\n    __tablename__ = '${table.name}'\n${lines.join("\n")}\n`;
  });
  return { path: "models.py", contents: header + blocks.join("\n\n") };
}

function pascal(name: string): string {
  return name
    .split(/[_\s-]+/)
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : ""))
    .join("");
}
